INSERT INTO orders_topping VALUES(1,'Pepperoni');
INSERT INTO orders_topping VALUES(2,'Sausage');
INSERT INTO orders_topping VALUES(3,'Mushrooms');
INSERT INTO orders_topping VALUES(4,'Onions');
INSERT INTO orders_topping VALUES(5,'Ham');
INSERT INTO orders_topping VALUES(6,'Canadian Bacon');
INSERT INTO orders_topping VALUES(7,'Pineapple');
INSERT INTO orders_topping VALUES(8,'Eggplant');
INSERT INTO orders_topping VALUES(9,'Tomato & Basil');
INSERT INTO orders_topping VALUES(10,'Green Peppers');
INSERT INTO orders_topping VALUES(11,'Hamburger');
INSERT INTO orders_topping VALUES(12,'Spinach');
INSERT INTO orders_topping VALUES(13,'Artichoke');
INSERT INTO orders_topping VALUES(14,'Buffalo Chicken');
INSERT INTO orders_topping VALUES(15,'Barbecue Chicken');
INSERT INTO orders_topping VALUES(16,'Anchovies');
INSERT INTO orders_topping VALUES(17,'Black Olives');
INSERT INTO orders_topping VALUES(18,'Fresh Garlic');
INSERT INTO orders_topping VALUES(19,'Zucchini');
INSERT INTO orders_pizzamenu VALUES(1,'Large','Regular',1745,'Cheese');
INSERT INTO orders_pizzamenu VALUES(2,'Small','Regular',1220,'Cheese');
INSERT INTO orders_pizzamenu VALUES(3,'Small','Regular',1320,'1 Topping');
INSERT INTO orders_pizzamenu VALUES(4,'Large','Regular',1945,'1 Topping');
INSERT INTO orders_pizzamenu VALUES(5,'Small','Regular',1470,'2 Toppings');
INSERT INTO orders_pizzamenu VALUES(6,'Large','Regular',2145,'2 Toppings');
INSERT INTO orders_pizzamenu VALUES(7,'Small','Regular',1570,'3 Toppings');
INSERT INTO orders_pizzamenu VALUES(8,'Large','Regular',2345,'3 Toppings');
INSERT INTO orders_pizzamenu VALUES(9,'Small','Regular',1725,'Special');
INSERT INTO orders_pizzamenu VALUES(10,'Large','Regular',2545,'Special');
INSERT INTO orders_subsmenu VALUES(1,'Small','Cheese',650);
INSERT INTO orders_subsmenu VALUES(2,'Large','Cheese',795);
INSERT INTO orders_subsmenu VALUES(3,'Small','Italian',650);
INSERT INTO orders_subsmenu VALUES(4,'Large','Italian',795);
INSERT INTO orders_subsmenu VALUES(5,'Small','Ham + Cheese',650);
INSERT INTO orders_subsmenu VALUES(6,'Large','Ham + Cheese',795);
INSERT INTO orders_subsmenu VALUES(7,'Small','Meatball',650);
INSERT INTO orders_subsmenu VALUES(8,'Large','Meatball',795);
INSERT INTO orders_subsmenu VALUES(9,'Small','Tuna',650);
INSERT INTO orders_subsmenu VALUES(10,'Large','Tuna',795);
INSERT INTO orders_subsmenu VALUES(11,'Small','Chicken Parmigiana',750);
INSERT INTO orders_subsmenu VALUES(12,'Large','Chicken Parmigiana',850);
INSERT INTO orders_subsmenu VALUES(13,'Small','Eggplant Parmigiana',650);
INSERT INTO orders_subsmenu VALUES(14,'Large','Eggplant Parmigiana',795);
INSERT INTO orders_subsmenu VALUES(15,'Small','Steak',650);
INSERT INTO orders_subsmenu VALUES(16,'Large','Steak',795);
INSERT INTO orders_subsmenu VALUES(17,'Small','Steak + Cheese',695);
INSERT INTO orders_subsmenu VALUES(18,'Large','Steak + Cheese',850);
INSERT INTO orders_subsmenu VALUES(19,'Small','Steak + Cheese + Mushrooms',745);
INSERT INTO orders_subsmenu VALUES(20,'Large','Steak + Cheese + Mushrooms',900);
INSERT INTO orders_subsmenu VALUES(21,'Small','Steak + Cheese + Green Peppers',745);
INSERT INTO orders_subsmenu VALUES(22,'Large','Steak + Cheese + Green Peppers',900);
INSERT INTO orders_subsmenu VALUES(23,'Small','Steak + Cheese + Onions',745);
INSERT INTO orders_subsmenu VALUES(24,'Large','Steak + Cheese + Onions',900);
INSERT INTO orders_subsmenu VALUES(26,'Large','Sausage, Peppers & Onions',850);
INSERT INTO orders_subsmenu VALUES(27,'Small','Hamburger',460);
INSERT INTO orders_subsmenu VALUES(28,'Large','Hamburger',745);
INSERT INTO orders_subsmenu VALUES(29,'Small','Cheeseburger',510);
INSERT INTO orders_subsmenu VALUES(30,'Large','Cheeseburger',745);
INSERT INTO orders_subsmenu VALUES(31,'Small','Fried Chicken',695);
INSERT INTO orders_subsmenu VALUES(32,'Large','Fried Chicken',850);
INSERT INTO orders_subsmenu VALUES(33,'Small','Veggie',695);
INSERT INTO orders_subsmenu VALUES(34,'Large','Veggie',850);
INSERT INTO orders_pastamenu VALUES(1,'Baked Ziti w/Mozzarella',650);
INSERT INTO orders_pastamenu VALUES(2,'Baked Ziti w/Meatballs',875);
INSERT INTO orders_pastamenu VALUES(3,'Baked Ziti w/Chicken',975);
INSERT INTO orders_saladmenu VALUES(1,'Garden Salad',625);
INSERT INTO orders_saladmenu VALUES(2,'Greek Salad',825);
INSERT INTO orders_saladmenu VALUES(3,'Antipasto',825);
INSERT INTO orders_saladmenu VALUES(4,'Salad w/Tuna',825);
INSERT INTO orders_dinnerplattermenu VALUES(1,'Small','Garden Salad',3500);
INSERT INTO orders_dinnerplattermenu VALUES(2,'Large','Garden Salad',60000);
INSERT INTO orders_dinnerplattermenu VALUES(3,'Small','Greek Salad',4500);
INSERT INTO orders_dinnerplattermenu VALUES(4,'Large','Greek Salad',7000);
INSERT INTO orders_dinnerplattermenu VALUES(5,'Small','Antipasto',4500);
INSERT INTO orders_dinnerplattermenu VALUES(6,'Large','Antipasto',7000);
INSERT INTO orders_dinnerplattermenu VALUES(7,'Small','Baked Ziti',3500);
INSERT INTO orders_dinnerplattermenu VALUES(8,'Large','Baked Ziti',6000);
INSERT INTO orders_dinnerplattermenu VALUES(9,'Small','Meatball Parm',4500);
INSERT INTO orders_dinnerplattermenu VALUES(10,'Large','Meatball Parm',7000);
INSERT INTO orders_dinnerplattermenu VALUES(11,'Small','Chicken Parm',4500);
INSERT INTO orders_dinnerplattermenu VALUES(12,'Large','Chicken Parm',8000);
INSERT INTO orders_cartitem VALUES(6,1,1745,'Pizza: large regular cheese 1@$17.45  $17.45',NULL);
INSERT INTO orders_cartitem VALUES(7,1,1745,'Pizza: large regular cheese 1@$17.45  $17.45',NULL);
