# Generated by Django 2.1.7 on 2019-03-31 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_pizzaprice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PizzaPrice',
            new_name='PizzaMenu',
        ),
    ]
