# Generated by Django 2.1.7 on 2019-03-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190331_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamenu',
            name='description',
            field=models.CharField(max_length=10),
        ),
    ]
