# Generated by Django 2.1.7 on 2019-03-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=50)),
                ('baseprice', models.IntegerField(verbose_name=30)),
            ],
        ),
    ]
