# Generated by Django 2.1.7 on 2019-03-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_subsmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsmenu',
            name='baseprice',
            field=models.IntegerField(),
        ),
    ]
