# Generated by Django 2.1.7 on 2019-03-31 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_dinnerplatter_pasta_salad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DinnerPlatter',
            new_name='DinnerPlatterMenu',
        ),
        migrations.RenameModel(
            old_name='Pasta',
            new_name='PastaMenu',
        ),
        migrations.RenameModel(
            old_name='Salad',
            new_name='SaladMenu',
        ),
    ]
