# Generated by Django 2.1.7 on 2019-03-31 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20190331_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinnerplattermenu',
            old_name='baseprice',
            new_name='price',
        ),
    ]
